name: Basic Rust CI with checks

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    if: github.ref != 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

#      - name: Install latest rust toolchain
#        uses: actions-rust-lang/setup-rust-toolchain@v1
#        with:
#          toolchain: stable

      - name: Test
        run: cargo clippy -- -Dwarnings && cargo test

      - name: Build release
        run: cargo build --release
