name: Rust CI with deploy on master

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: []

jobs:
  build:
    name: Build project
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

#      - name: Install latest rust toolchain
#        uses: actions-rust-lang/setup-rust-toolchain@v1
#        with:
#          toolchain: stable

      - name: Test
        run: cargo clippy -- -Dwarnings && cargo test

      - name: Build release
        run: cargo build --release

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: 'target/doc'

      - name: Publish to crates.io
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}